format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[directory]
truncation_length = 2

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "
